// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PushDevice is the golang structure of table push_device for DAO operations like Where/Data.
type PushDevice struct {
	g.Meta         `orm:"table:push_device, do:true"`
	Id             interface{} // 推送设备表主键id
	DeviceName     interface{} // 设备名称
	BaseUrl        interface{} // 推送基础URL
	ServiceIdList  interface{} // 推送服务id列表
	LatestPushTime *gtime.Time // 最近推送时间
	DeviceStatus   interface{} // 设备状态
	CreateTime     *gtime.Time // 创建时间
}
