// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PushLog is the golang structure of table push_log for DAO operations like Where/Data.
type PushLog struct {
	g.Meta      `orm:"table:push_log, do:true"`
	Id          interface{} // 推送日志表主键id
	PushInfo    interface{} // 推送内容
	PushService interface{} // 推送服务
	PushTime    *gtime.Time // 推送时间
	PushStatus  interface{} // 推送状态
	ErrInfo     interface{} // 错误日志
}
