# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name: "speed_cron"
    arch: "amd64,arm64" # all,386,amd64,arm64
    system: "windows,darwin,linux" # all,linux,darwin,windows....
    packSrc: ""
    version: "release"
    mod: ""
    cgo: 0
