// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"kes-cron/internal/dao/internal"
)

// internalNetSpeedDeviceDao is internal type for wrapping internal DAO implements.
type internalNetSpeedDeviceDao = *internal.NetSpeedDeviceDao

// netSpeedDeviceDao is the data access object for table net_speed_device.
// You can define custom methods on it to extend its functionality as you wish.
type netSpeedDeviceDao struct {
	internalNetSpeedDeviceDao
}

var (
	// NetSpeedDevice is globally public accessible object for table net_speed_device operations.
	NetSpeedDevice = netSpeedDeviceDao{
		internal.NewNetSpeedDeviceDao(),
	}
)

// Fill with you ideas below.
