// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"kes-cron/internal/dao/internal"
)

// internalNetSpeedTaskDao is internal type for wrapping internal DAO implements.
type internalNetSpeedTaskDao = *internal.NetSpeedTaskDao

// netSpeedTaskDao is the data access object for table net_speed_task.
// You can define custom methods on it to extend its functionality as you wish.
type netSpeedTaskDao struct {
	internalNetSpeedTaskDao
}

var (
	// NetSpeedTask is globally public accessible object for table net_speed_task operations.
	NetSpeedTask = netSpeedTaskDao{
		internal.NewNetSpeedTaskDao(),
	}
)

// Fill with you ideas below.
