// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"kes-network-watcher/internal/dao/internal"
)

// internalNetSpeedDataDao is internal type for wrapping internal DAO implements.
type internalNetSpeedDataDao = *internal.NetSpeedDataDao

// netSpeedDataDao is the data access object for table net_speed_data.
// You can define custom methods on it to extend its functionality as you wish.
type netSpeedDataDao struct {
	internalNetSpeedDataDao
}

var (
	// NetSpeedData is globally public accessible object for table net_speed_data operations.
	NetSpeedData = netSpeedDataDao{
		internal.NewNetSpeedDataDao(),
	}
)

// Fill with you ideas below.
