// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PushService is the golang structure for table push_service.
type PushService struct {
	Id              uint        `json:"id"                ` // 推送服务表主键id
	ServiceName     string      `json:"service_name"      ` // 推送服务名称
	ServiceSign     string      `json:"service_sign"      ` // 推送服务标识
	ServiceStatus   bool        `json:"service_status"    ` // 服务状态
	ServicePushTime *gtime.Time `json:"service_push_time" ` // 服务最新推送时间
}
