// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PushDevice is the golang structure for table push_device.
type PushDevice struct {
	Id             uint        `json:"id"               ` // 推送设备表主键id
	DeviceName     string      `json:"device_name"      ` // 设备名称
	BaseUrl        string      `json:"base_url"         ` // 推送基础URL
	ServiceIdList  string      `json:"service_id_list"  ` // 推送服务id列表
	LatestPushTime *gtime.Time `json:"latest_push_time" ` // 最近推送时间
	DeviceStatus   bool        `json:"device_status"    ` // 设备状态
	CreateTime     *gtime.Time `json:"create_time"      ` // 创建时间
}
