name: Build and push Docker image

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: echo "CURRENT_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Get Git Commit Log
        id: git-commit-log
        run: echo "GIT_COMMIT_LOG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"

      - name: Get Build Time
        id: build-time
        run: echo "BUILD_TIME=${{ steps.current-time.outputs.readableTime }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} . --build-arg GIT_TAG=${{env.CURRENT_VERSION}} --build-arg GIT_COMMIT_LOG="${{env.GIT_COMMIT_LOG}}" --build-arg BUILD_TIME="${{env.BUILD_TIME}}"

      - name: Print environment variables
        run: |
          echo "${{env.GIT_COMMIT_LOG}}"
          echo "${{env.BUILD_TIME}}"
          echo "${{env.CURRENT_VERSION}}"

      - name: Tag Docker image
        run: docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:${{ env.CURRENT_VERSION }}

      - name: Tag Docker image as latest
        run: docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

      - name: Push Docker image
        run: |
            docker push $IMAGE_NAME:${{ env.CURRENT_VERSION }}
            docker push $IMAGE_NAME:latest